const translations = {
  "English": {
    "menu": "menu",
    "myOrders": "My Orders",
    "menuCheck": "Checkout our",
    "buy": "Buy now",
    "status": "status",
    "totalPrice": "Total Price",
    "Products": "Products",
    "modify": "Modify",
    "cancel": "Cancel",
    "rate": "Rate",
    "rated": "Rated",
    "preparing": "Preparing",
    "completed": "Completed",
    "pending": "Pending",
    "newOrder": "Add a new Order",
    "rateSubmit": "Submit Ratings",
    "email": "email",
    "password": "password",
    "tabnum": "Table Number",
    "signin": "Sign In",
    "backToMenu": "Back to menu",
    "placeOrder": "Place the order",
    "updateOrder": "Update the order",
    "remove": "Remove",
    "removeConfirm": "are you sure you want to remove this",
    "yes": "Yes",
    "no": "No",
    "confirm": "Confirm",
    "rateYourProducts": "Rate Your Products",
    "goToMyOrders": "Go to My Orders",
    "thankYouForRating": "Thank you for rating!",
    "goToMenu": "Go to Menu",
    "pleaseSelectItems": "Please select some items from our menu.",
    "price": "Price"
  },
  "French": {
    "price": "Prix",
    "menu": "menu",
    "myOrders": "Mes commandes",
    "menuCheck": "consultez notre",
    "buy": "Achetez maintenant",
    "status": "statut",
    "totalPrice": "Prix total",
    "Products": "Produits",
    "modify": "Modifier",
    "cancel": "annuler",
    "rate": "Évaluer",
    "rated": "Évalué",
    "preparing": "En préparation",
    "completed": "Terminé",
    "pending": "En attente",
    "newOrder": "Ajouter une nouvelle commande",
    "rateSubmit": "Soumettre les évaluations",
    "email": "e-mail",
    "password": "mot de passe",
    "tabnum": "Numéro de table",
    "signin": "Se connecter",
    "backToMenu": "Retour au menu",
    "placeOrder": "Passer la commande",
    "updateOrder": "Mettre à jour la commande",
    "remove": "Supprimer",
    "removeConfirm": "êtes-vous sûr de vouloir supprimer ceci",
    "yes": "Oui",
    "no": "Non",
    "confirm": "Confirmer",
    "rateYourProducts": "Évaluez vos produits",
    "goToMyOrders": "Aller à mes commandes",
    "thankYouForRating": "Merci pour votre évaluation !",
    "goToMenu": "Aller au menu",
    "pleaseSelectItems": "Veuillez sélectionner des articles de notre menu."
  },
  "Italian": {
    "price": "Prezzo",
    "menu": "menu",
    "myOrders": "I miei ordini",
    "menuCheck": "scopri il nostro",
    "buy": "Acquista ora",
    "status": "stato",
    "totalPrice": "Prezzo totale",
    "Products": "Prodotti",
    "modify": "Modificare",
    "cancel": "annullare",
    "rate": "Valutare",
    "rated": "Valutato",
    "preparing": "In preparazione",
    "completed": "Completato",
    "pending": "In sospeso",
    "newOrder": "Aggiungi un nuovo ordine",
    "rateSubmit": "Invia valutazioni",
    "email": "email",
    "password": "password",
    "tabnum": "Numero del tavolo",
    "signin": "Accedi",
    "backToMenu": "Torna al menu",
    "placeOrder": "Effettua l'ordine",
    "updateOrder": "Aggiorna l'ordine",
    "remove": "Rimuovere",
    "removeConfirm": "sei sicuro di voler rimuovere questo",
    "yes": "Sì",
    "no": "No",
    "confirm": "Confermare",
    "rateYourProducts": "Valuta i tuoi prodotti",
    "goToMyOrders": "Vai ai miei ordini",
    "thankYouForRating": "Grazie per la tua valutazione!",
    "goToMenu": "Vai al menu",
    "pleaseSelectItems": "Si prega di selezionare alcuni elementi dal nostro menu."
  }
}

;

export default translations;
