const translations = {
  English: {
    menu: "menu",
    myOrders: "My Orders",
    myOrder: "My Order",
    menuCheck: "Checkout our",
    buy: "Buy now",
    status: "status",
    totalPrice: "Total Price",
    Products: "Products",
    modify: "Modify",
    cancel: "Cancel",
    rate: "Rate",
    rated: "Rated",
    completed: "Completed",
    newOrder: "Add a new Order",
    rateSubmit: "Submit Ratings",
    email: "email",
    password: "password",
    tabnum: "Table N°",
    signin: "Sign In",

    placeOrder: "Place the order",
    updateOrder: "Update the order",
    remove: "Remove",
    removeConfirm: "are you sure you want to remove this",
    yes: "Yes",
    no: "No",
    confirm: "Confirm",
    rateYourProducts: "Rate Your Products",
    goToMyOrders: "Go to My Orders",
    thankYouForRating: "Thank you for rating!",
    goToMenu: "Go to Menu",
    pleaseSelectItems: "Please select some items from our menu.",
    price: "Price",
    welcomeTo: "Welcome to",
    comment: "Comment",
    addYourComment: "Add Your Comment",
    placeTheOrder: "Place the Order",
    pending: "Pending",
    preparing: "Preparing",
    cancelled: "Cancelled",
    tip: "Tip",
    chooseYourTip: "Choose Your Tip",
    enterCustomTipAmount: "Enter Custom Tip Amount",
    submitTip: "Submit Tip",
    thankYouForYourTip: "Thank You for Your Tip",
    tipped: "Tipped",
    total: "Total",
    qty: "Qty",
    backToMenu: "Back to menu",
    totalWithoutTips: "Total (without tips)",
    totalWithTips: "Total (with tips)",
  },
  French: {
    price: "Prix",
    menu: "menu",
    myOrders: "Mes commandes",
    myOrder: "Ma Commande",
    menuCheck: "consultez notre",
    buy: "Achetez maintenant",
    status: "statut",
    totalPrice: "Prix total",
    Products: "Produits",
    modify: "Modifier",
    cancel: "annuler",
    rate: "Évaluer",
    rated: "Évalué",
    newOrder: "Ajouter une nouvelle commande",
    rateSubmit: "Soumettre les évaluations",
    email: "e-mail",
    password: "mot de passe",
    tabnum: "Table Numéro",
    signin: "Se connecter",
    placeOrder: "Passer la commande",
    updateOrder: "Mettre à jour la commande",
    remove: "Supprimer",
    removeConfirm: "êtes-vous sûr de vouloir supprimer ceci",
    yes: "Oui",
    no: "Non",
    confirm: "Confirmer",
    rateYourProducts: "Évaluez vos produits",
    goToMyOrders: "Aller à mes commandes",
    thankYouForRating: "Merci pour votre évaluation !",
    goToMenu: "Aller au menu",
    pleaseSelectItems: "Veuillez sélectionner des articles de notre menu.",
    welcomeTo: "bienvenue chez",
    backToMenu: "Retour au menu",
    comment: "Commentaire",
    addYourComment: "Ajouter votre commentaire",
    placeTheOrder: "Passer la commande",
    pending: "En attente",
    preparing: "En préparation",
    completed: "Terminé",
    cancelled: "Annulé",
    tip: "Pourboire",
    chooseYourTip: "Choisissez votre pourboire",
    enterCustomTipAmount: "Entrez un montant de pourboire personnalisé",
    submitTip: "Soumettre le pourboire",
    thankYouForYourTip: "Merci pour votre pourboire",
    tipped: "Pourboire donné",
    total: "Total",
    qty: "Qté",
    totalWithoutTips: "Total (hors pourboires)",
    totalWithTips: "Total (avec pourboires)",
  },
  Italian: {
    welcomeTo: "benvenuti a",
    price: "Prezzo",
    menu: "menu",
    myOrders: "I miei ordini",
    myOrder: "Il mio ordine",
    menuCheck: "scopri il nostro",
    buy: "Acquista ora",
    status: "stato",
    totalPrice: "Prezzo totale",
    Products: "Prodotti",
    modify: "Modificare",
    cancel: "annullare",
    rate: "Valutare",
    rated: "Valutato",
    newOrder: "Aggiungi un nuovo ordine",
    rateSubmit: "Invia valutazioni",
    email: "email",
    password: "password",
    tabnum: "Numero del tavolo",
    signin: "Accedi",
    placeOrder: "Effettua l'ordine",
    updateOrder: "Aggiorna l'ordine",
    remove: "Rimuovere",
    removeConfirm: "sei sicuro di voler rimuovere questo",
    yes: "Sì",
    no: "No",
    confirm: "Confermare",
    rateYourProducts: "Valuta i tuoi prodotti",
    goToMyOrders: "Vai ai miei ordini",
    thankYouForRating: "Grazie per la tua valutazione!",
    goToMenu: "Vai al menu",
    pleaseSelectItems:
      "Si prega di selezionare alcuni elementi dal nostro menu.",
    backToMenu: "Torna al menu",
    comment: "Commento",
    addYourComment: "Aggiungi il tuo commento",
    placeTheOrder: "Effettua l'ordine",
    pending: "In attesa",
    preparing: "In preparazione",
    completed: "Completato",
    cancelled: "Annullato",
    tip: "Mancia",
    chooseYourTip: "Scegli la tua mancia",
    enterCustomTipAmount: "Inserisci un importo personalizzato per la mancia",
    submitTip: "Invia mancia",
    thankYouForYourTip: "Grazie per la tua mancia",
    tipped: "Mancia data",
    total: "Totale",
    qty: "Quantità",
    totalWithoutTips: "Totale (senza mance)",
    totalWithTips: "Totale (con mance)",
  },
};

export default translations;
